# Generated by Django 4.1 on 2022-08-14 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='upper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='上位カテゴリ'),
        ),
        migrations.AlterField(
            model_name='content',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article', verbose_name='記事'),
        ),
        migrations.AlterField(
            model_name='headline',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.content', verbose_name='コンテンツ'),
        ),
        migrations.AlterField(
            model_name='image',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.content', verbose_name='コンテンツ'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.content', verbose_name='コンテンツ'),
        ),
    ]
