# Generated by Django 4.1 on 2022-08-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='second_content_text',
        ),
    ]
