# Generated by Django 4.1 on 2022-08-18 17:40

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_editorjs.fields.EditorJsField(verbose_name='内容'),
        ),
    ]
