# Generated by Django 4.1 on 2022-08-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_article_second_content_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='second_content',
            new_name='content',
        ),
    ]
