# Generated by Django 4.1 on 2022-08-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.CharField(default='画像', max_length=200, verbose_name='説明'),
        ),
    ]
