# Generated by Django 4.1 on 2022-08-21 16:53

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=core.models.local_now, verbose_name='投稿日'),
        ),
        migrations.AlterField(
            model_name='article',
            name='renew_date',
            field=models.DateTimeField(default=core.models.local_now, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='category',
            name='upper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lowers', to='core.category', verbose_name='上位カテゴリ'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='pub_date',
            field=models.DateTimeField(default=core.models.local_now, verbose_name='登録日'),
        ),
    ]
