# Generated by Django 4.1 on 2022-08-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='size',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], verbose_name='階層'),
        ),
    ]
