# Generated by Django 4.1 on 2022-08-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_article_pub_date_alter_article_renew_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='これがカテゴリの説明文です。', verbose_name='カテゴリの説明文'),
        ),
    ]
