# Generated by Django 4.1 on 2022-08-13 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_image_content_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='inner_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed.')], verbose_name='内部的カテゴリ名'),
        ),
    ]
