# Generated by Django 4.1 on 2022-08-13 15:15

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_category_inner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=core.models.get_admin_user, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=core.models.get_home_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.category'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='display_name',
            field=models.CharField(default='nanashi-san', max_length=100, verbose_name='表示名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='inner_name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', '半角英数字とアンダースコアのみ使用可能です。')], verbose_name='内部的カテゴリ名'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='カテゴリ名'),
        ),
    ]
